nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'X-Auth-Token', 'X-Requested-With', 'Cache-Control']
        expose_headers: ['X-Auth-Token']
        max_age: 3600
    paths:
        '^/': ~