nelmio_api_doc:
    documentation:
        info:
            title: "SocialApp API Documentation"
            description: ''
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/v1.0(?!/docs$) # Accepts routes under /v1.0 except /v1.0/docs
