monolog:
    channels: ["api"]
    handlers:
        api:
            type:  rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            channels: ["api"]
            max_files: 14
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]